### ISSUE TITLE
一个小建议

### ISSUE THREAD

**Issue by lingMori** [KUN1007/kungalgame-stickers#1]
可以解包，然后批量处理😤

**Comment by KunMoe** [comment]
> 可以解包，然后批量处理😤

非常感谢你的建议！

这里的解包的话具体指的是什么呀

我能想到的可能是
1. 解包 galgame
2. 批量合成人物立绘
3. 截图

如果你的想法是这样的话，我做了这些考虑

这个方法的缺点是：
1. 不能及时的边玩游戏边截图，没有那种感觉！
2. 部分游戏立绘合成较为难做
3. 部分游戏较为难以解包

优点是：
1. 截图较为可控
2. 可以截出透明背景（其实我较为喜欢有背景的图，因为有感觉）

于是考量了一下我就这么边玩边截图了 www

如果我对你的建议理解有误的话，请你务必纠正我的错误。

**Comment by lingMori** [comment]
是的，你的考量是对的。
考虑到背景的问题的话，确实如此，感觉最重要！
继续加油👏
某种程度上算是优秀的数据集了 : ）
