### ISSUE TITLE
[nit] introduction.mp4 cannot be played by Firefox

### ISSUE THREAD

**Issue by zjkmxy** [KUN1007/kungalgame-stickers#4]
Firefox和Safari不能正常播放 https://sticker.kungal.com/introduction.mp4
Chromium系的Chrome和Edge都可以。
感覺可能是MP4內部編碼方式的問題。

**Comment by KunMoe** [comment]
感谢反馈，经过我的测试，好像是 Vercel 的问题，暂时无法解决，以后再想想办法

**Comment by KunMoe** [comment]
已解决
